import {birds} from "../images/allImages";

export const birdCards = [
  { id: 0, src: birds["americanCoot.png"], name: "American Coot", flightNums: [1, 2], season: "winter", habitat: ["wetland", "wildGrass"] },
  { id: 1, src: birds["americanCrow.png"], name: "American Crow", flightNums: [3, 4], season: "any", habitat: ["nuts", "lawn"] },
  { id: 2, src: birds["americanGoldfinch.png"], name: "American Goldfinch", flightNums: [5, 6], season: "spring", habitat: ["seeds", "trees"] },
  { id: 3, src: birds["americanRobin.png"], name: "American Robin", flightNums: [1, 2], season: "spring", habitat: ["insects", "lawn"] },
  { id: 4, src: birds["americanWigeon.png"], name: "American Wigeon", flightNums: [3,4], season: "autumn", habitat: ["runningWater", "wildGrass"] },
  { id: 5, src: birds["annasHummingbird.png"], name: "Anna's Hummingbird", flightNums: [5,6], season: "any", habitat: ["trees", "bushesAndFlowers"] },
  { id: 6, src: birds["bandTailedPigeon.png"], name: "Band-Tailed Pigeon", flightNums: [1,2], season: "summer", habitat: ["trees", "nuts"] },
  { id: 7, src: birds["beltedKingfisher.png"], name: "Belted Kingfisher", flightNums: [3,4], season: "autumn", habitat: ["fish", "wetland"] },
  { id: 8, src: birds["bewicksWren.png"], name: "Bewick's Wren", flightNums: [5,6], season: "autumn", habitat: ["seeds", "trees"] },
  { id: 10, src: birds["blackCappedChickadee.png"], name: "Black-Capped Chickadee", flightNums: [1,2], season: "any", habitat: ["nuts", "trees"] },
  { id: 10, src: birds["bufflehead.png"], name: "Bufflehead", flightNums: [3,4], season: "winter", habitat: ["runningWater", "wildGrass"] },
  { id: 11, src: birds["bushtit.png"], name: "Bushtit", flightNums: [5,6], season: "winter", habitat: ["insects", "trees"] },
  { id: 12, src: birds["canadaGoose.png"], name: "Canada Goose", flightNums: [1,2], season: "any", habitat: ["insects", "wetland"] },
  { id: 13, src: birds["darkEyedJunco.png"], name: "Dark Eyed Junco", flightNums: [5,6], season: "any", habitat: ["seeds", "bushesAndFlowers"] },
  { id: 14, src: birds["doubleCrestedCormorant.png"], name: "Double-Crested Cormorant", flightNums: [1,2], season: "spring", habitat: ["fish", "wetland"] },
  { id: 15, src: birds["gadwall.png"], name: "Gadwall", flightNums: [3,4], season: "autumn", habitat: ["runningWater", "wildGrass"] },
  { id: 16, src: birds["goldenCrownedSparrow.png"], name: "Golden-Crowned Sparrow", flightNums: [5,6], season: "winter", habitat: ["seeds", "bushesAndFlowers"] },
  { id: 17, src: birds["greatBlueHeron.png"], name: "Great Blue Heron", flightNums: [1,2], season: "summer", habitat: ["fish", "wetland"] },
  { id: 18, src: birds["greenHeron.png"], name: "Green Heron", flightNums: [3,4], season: "spring", habitat: ["fish", "runningWater"] },
  { id: 19, src: birds["greenWingedTeal.png"], name: "Green-Winged Teal", flightNums: [5,6], season: "autumn", habitat: ["runningWater", "wildGrass"] },
  { id: 20, src: birds["hoodedMerganser.png"], name: "Hooded Merganser", flightNums: [1,2], season: "autumn", habitat: ["runningWater", "fish"] },
  { id: 21, src: birds["houseFinch.png"], name: "House Finch", flightNums: [3,4], season: "winter", habitat: ["nuts", "bushesAndFlowers"] },
  { id: 22, src: birds["killdeer.png"], name: "Killdeer", flightNums: [5,6], season: "spring", habitat: ["insects", "lawn"] },
  { id: 23, src: birds["mallard.png"], name: "Mallard", flightNums: [1,2], season: "any", habitat: ["wetland", "wildGrass"] },
  { id: 24, src: birds["mourningDove.png"], name: "Mourning Dove", flightNums: [3,4], season: "summer", habitat: ["nuts", "lawn"] },
  { id: 25, src: birds["northernFlicker.png"], name: "Northern Flicker", flightNums: [5,6], season: "spring", habitat: ["insects", "lawn"] },
  { id: 26, src: birds["piedBilledGrebe.png"], name: "Pied-Billed Grebe", flightNums: [1,2], season: "winter", habitat: ["fish", "runningWater"] },
  { id: 27, src: birds["pileatedWoodpecker.png"], name: "Pileated Woodpecker", flightNums: [3,4], season: "summer", habitat: ["insects", "trees"] },
  { id: 28, src: birds["redBreastedNuthatch.png"], name: "Red-Breasted Nuthatch", flightNums: [5,6], season: "winter", habitat: ["nuts", "trees"] },
  { id: 29, src: birds["redWingedBlackbird.png"], name: "Red-Winged Blackbird", flightNums: [1,2], season: "spring", habitat: ["insects", "wetland"] },
  { id: 30, src: birds["rubyCrownedKinglet.png"], name: "Ruby-Crowned Kinglet", flightNums: [3,4], season: "summer", habitat: ["insects", "trees"] },
  { id: 31, src: birds["rufousHummingbird.png"], name: "Rufous Hummingbird", flightNums: [5,6], season: "spring", habitat: ["trees", "bushesAndFlowers"] },
  { id: 32, src: birds["songSparrow.png"], name: "Song Sparrow", flightNums: [1,2], season: "any", habitat: ["seeds", "bushesAndFlowers"] },
  { id: 33, src: birds["spottedTowhee.png"], name: "Spotted Towhee", flightNums: [3,4], season: "summer", habitat: ["seeds", "bushesAndFlowers"] },
  { id: 34, src: birds["stellersJay.png"], name: "Steller's Jay", flightNums: [5,6], season: "any", habitat: ["nuts", "lawn"] },
  { id: 35, src: birds["variedThrush.png"], name: "Varied Thrush", flightNums: [3,4], season: "winter", habitat: ["seeds", "lawn"] },
  { id: 36, src: birds["whiteCrownedSparrow.png"], name: "White-Crowned Sparrow", flightNums: [5,6], season: "spring", habitat: ["seeds", "bushesAndFlowers"] },
  { id: 37, src: birds["woodDuck.png"], name: "Wood Duck", flightNums: [1,2], season: "spring", habitat: ["wetland", "wildGrass"] }
];